class PIDDSRules:

	def  DTRules(self):
		
		rules = []
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '>', 'value' : '166.500'}, {'key' : 'BloodPressure', 'operator' : '>', 'value' : '93'}, {'key' : 'Pregnancies', 'operator' : '>', 'value' : '7.500'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '>', 'value' : '166.500'}, {'key' : 'BloodPressure', 'operator' : '>', 'value' : '93'}, {'key' : 'Pregnancies', 'operator' : '=', 'value' : '7.500'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '186'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '>', 'value' : '166.500'}, {'key' : 'BloodPressure', 'operator' : '>', 'value' : '93'}, {'key' : 'Pregnancies', 'operator' : '=', 'value' : '7.500'}, {'key' : 'Glucose', 'operator' : '=', 'value' : '186'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '>', 'value' : '166.500'}, {'key' : 'BloodPressure', 'operator' : '=', 'value' : '93'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '=', 'value' : '166.500'}, {'key' : 'Pregnancies', 'operator' : '>', 'value' : '13.500'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '=', 'value' : '166.500'}, {'key' : 'Pregnancies', 'operator' : '=', 'value' : '13.500'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '154.500'}, {'key' : 'Insulin', 'operator' : '>', 'value' : '542.500'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '=', 'value' : '166.500'}, {'key' : 'Pregnancies', 'operator' : '=', 'value' : '13.500'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '154.500'}, {'key' : 'Insulin', 'operator' : '=', 'value' : '542.500'}, {'key' : 'DiabetesPedigreeFunction', 'operator' : '>', 'value' : '0.141'}, {'key' : 'Age', 'operator' : '>', 'value' : '53.500'}, {'key' : 'Pregnancies', 'operator' : '>', 'value' : '3.500'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '=', 'value' : '166.500'}, {'key' : 'Pregnancies', 'operator' : '=', 'value' : '13.500'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '154.500'}, {'key' : 'Insulin', 'operator' : '=', 'value' : '542.500'}, {'key' : 'DiabetesPedigreeFunction', 'operator' : '>', 'value' : '0.141'}, {'key' : 'Age', 'operator' : '>', 'value' : '53.500'}, {'key' : 'Pregnancies', 'operator' : '=', 'value' : '3.500'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '=', 'value' : '166.500'}, {'key' : 'Pregnancies', 'operator' : '=', 'value' : '13.500'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '154.500'}, {'key' : 'Insulin', 'operator' : '=', 'value' : '542.500'}, {'key' : 'DiabetesPedigreeFunction', 'operator' : '>', 'value' : '0.141'}, {'key' : 'Age', 'operator' : '=', 'value' : '53.500'}, {'key' : 'SkinThickness', 'operator' : '>', 'value' : '42'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '=', 'value' : '166.500'}, {'key' : 'Pregnancies', 'operator' : '=', 'value' : '13.500'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '154.500'}, {'key' : 'Insulin', 'operator' : '=', 'value' : '542.500'}, {'key' : 'DiabetesPedigreeFunction', 'operator' : '>', 'value' : '0.141'}, {'key' : 'Age', 'operator' : '=', 'value' : '53.500'}, {'key' : 'SkinThickness', 'operator' : '=', 'value' : '42'}, {'key' : 'BloodPressure', 'operator' : '>', 'value' : '69'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '=', 'value' : '166.500'}, {'key' : 'Pregnancies', 'operator' : '=', 'value' : '13.500'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '154.500'}, {'key' : 'Insulin', 'operator' : '=', 'value' : '542.500'}, {'key' : 'DiabetesPedigreeFunction', 'operator' : '>', 'value' : '0.141'}, {'key' : 'Age', 'operator' : '=', 'value' : '53.500'}, {'key' : 'SkinThickness', 'operator' : '=', 'value' : '42'}, {'key' : 'BloodPressure', 'operator' : '=', 'value' : '69'}, {'key' : 'BloodPressure', 'operator' : '>', 'value' : '63'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '=', 'value' : '166.500'}, {'key' : 'Pregnancies', 'operator' : '=', 'value' : '13.500'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '154.500'}, {'key' : 'Insulin', 'operator' : '=', 'value' : '542.500'}, {'key' : 'DiabetesPedigreeFunction', 'operator' : '>', 'value' : '0.141'}, {'key' : 'Age', 'operator' : '=', 'value' : '53.500'}, {'key' : 'SkinThickness', 'operator' : '=', 'value' : '42'}, {'key' : 'BloodPressure', 'operator' : '=', 'value' : '69'}, {'key' : 'BloodPressure', 'operator' : '=', 'value' : '63'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '=', 'value' : '166.500'}, {'key' : 'Pregnancies', 'operator' : '=', 'value' : '13.500'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '154.500'}, {'key' : 'Insulin', 'operator' : '=', 'value' : '542.500'}, {'key' : 'DiabetesPedigreeFunction', 'operator' : '=', 'value' : '0.141'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '=', 'value' : '166.500'}, {'key' : 'Pregnancies', 'operator' : '=', 'value' : '13.500'}, {'key' : 'Glucose', 'operator' : '=', 'value' : '154.500'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '101.500'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '=', 'value' : '166.500'}, {'key' : 'Pregnancies', 'operator' : '=', 'value' : '13.500'}, {'key' : 'Glucose', 'operator' : '=', 'value' : '154.500'}, {'key' : 'Glucose', 'operator' : '=', 'value' : '101.500'}, {'key' : 'Insulin', 'operator' : '>', 'value' : '212.500'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '=', 'value' : '166.500'}, {'key' : 'Pregnancies', 'operator' : '=', 'value' : '13.500'}, {'key' : 'Glucose', 'operator' : '=', 'value' : '154.500'}, {'key' : 'Glucose', 'operator' : '=', 'value' : '101.500'}, {'key' : 'Insulin', 'operator' : '=', 'value' : '212.500'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '22'}, {'key' : 'DiabetesPedigreeFunction', 'operator' : '>', 'value' : '1.116'}, {'key' : 'Pregnancies', 'operator' : '>', 'value' : '2.500'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '=', 'value' : '166.500'}, {'key' : 'Pregnancies', 'operator' : '=', 'value' : '13.500'}, {'key' : 'Glucose', 'operator' : '=', 'value' : '154.500'}, {'key' : 'Glucose', 'operator' : '=', 'value' : '101.500'}, {'key' : 'Insulin', 'operator' : '=', 'value' : '212.500'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '22'}, {'key' : 'DiabetesPedigreeFunction', 'operator' : '>', 'value' : '1.116'}, {'key' : 'Pregnancies', 'operator' : '=', 'value' : '2.500'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '=', 'value' : '166.500'}, {'key' : 'Pregnancies', 'operator' : '=', 'value' : '13.500'}, {'key' : 'Glucose', 'operator' : '=', 'value' : '154.500'}, {'key' : 'Glucose', 'operator' : '=', 'value' : '101.500'}, {'key' : 'Insulin', 'operator' : '=', 'value' : '212.500'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '22'}, {'key' : 'DiabetesPedigreeFunction', 'operator' : '=', 'value' : '1.116'}, {'key' : 'Insulin', 'operator' : '>', 'value' : '150'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '96.500'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '=', 'value' : '166.500'}, {'key' : 'Pregnancies', 'operator' : '=', 'value' : '13.500'}, {'key' : 'Glucose', 'operator' : '=', 'value' : '154.500'}, {'key' : 'Glucose', 'operator' : '=', 'value' : '101.500'}, {'key' : 'Insulin', 'operator' : '=', 'value' : '212.500'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '22'}, {'key' : 'DiabetesPedigreeFunction', 'operator' : '=', 'value' : '1.116'}, {'key' : 'Insulin', 'operator' : '>', 'value' : '150'}, {'key' : 'Glucose', 'operator' : '=', 'value' : '96.500'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '=', 'value' : '166.500'}, {'key' : 'Pregnancies', 'operator' : '=', 'value' : '13.500'}, {'key' : 'Glucose', 'operator' : '=', 'value' : '154.500'}, {'key' : 'Glucose', 'operator' : '=', 'value' : '101.500'}, {'key' : 'Insulin', 'operator' : '=', 'value' : '212.500'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '22'}, {'key' : 'DiabetesPedigreeFunction', 'operator' : '=', 'value' : '1.116'}, {'key' : 'Insulin', 'operator' : '=', 'value' : '150'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '=', 'value' : '166.500'}, {'key' : 'Pregnancies', 'operator' : '=', 'value' : '13.500'}, {'key' : 'Glucose', 'operator' : '=', 'value' : '154.500'}, {'key' : 'Glucose', 'operator' : '=', 'value' : '101.500'}, {'key' : 'Insulin', 'operator' : '=', 'value' : '212.500'}, {'key' : 'Glucose', 'operator' : '=', 'value' : '22'}, {'key' : 'Pregnancies', 'operator' : '>', 'value' : '3'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '=', 'value' : '166.500'}, {'key' : 'Pregnancies', 'operator' : '=', 'value' : '13.500'}, {'key' : 'Glucose', 'operator' : '=', 'value' : '154.500'}, {'key' : 'Glucose', 'operator' : '=', 'value' : '101.500'}, {'key' : 'Insulin', 'operator' : '=', 'value' : '212.500'}, {'key' : 'Glucose', 'operator' : '=', 'value' : '22'}, {'key' : 'Pregnancies', 'operator' : '=', 'value' : '3'}], 'conclusion' : 'No'})
		
		return rules
	
	def PartRules(self):
		
		rules = []
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '<=', 'value' : '127'}, {'key' : 'BMI', 'operator' : '<=', 'value' : '26.4'}, {'key' : 'Pregnancies ', 'operator' : '<=', 'value' : '7'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '>', 'value' : '154'}, {'key' : 'BMI', 'operator' : '>', 'value' : '29.8'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '<=', 'value' : '99'}, {'key' : 'Age', 'operator' : '<=', 'value' : '25'}, {'key' : 'Age', 'operator' : '<=', 'value' : '22'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Age', 'operator' : '<=', 'value' : '28'}, {'key' : 'SkinThickness', 'operator' : '>', 'value' : '0'}, {'key' : 'SkinThickness', 'operator' : '<=', 'value' : '24'}, {'key' : 'Age', 'operator' : '>', 'value' : '22'}, {'key' : 'Pregnancies', 'operator' : '<=', 'value' : '3'}, {'key' : 'Glucose', 'operator' : '<=', 'value' : '127'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '<=', 'value' : '99'}, {'key' : 'Insulin', 'operator' : '<=', 'value' : '88'}, {'key' : 'Insulin', 'operator' : '<=', 'value' : '18'}, {'key' : 'SkinThickness', 'operator' : '>', 'value' : '22'}, {'key' : 'Pregnancies', 'operator' : '<=', 'value' : '3'}, {'key' : 'Glucose', 'operator' : '<=', 'value' : '21'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Age', 'operator' : '<=', 'value' : '24'}, {'key' : 'SkinThickness', 'operator' : '>', 'value' : '0'}, {'key' : 'BMI', 'operator' : '<=', 'value' : '33.3'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'BloodPressure', 'operator' : '<=', 'value' : '40'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '130'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '<=', 'value' : '107'}, {'key' : 'DiabetesPedigreeFunction', 'operator' : '<=', 'value' : '0.229'}, {'key' : 'BloodPressure', 'operator' : '<=', 'value' : '80'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Pregnancies', 'operator' : '<=', 'value' : '6'}, {'key' : 'Glucose', 'operator' : '<=', 'value' : '112'}, {'key' : 'BloodPressure', 'operator' : '<=', 'value' : '88'}, {'key' : 'Age', 'operator' : '<=', 'value' : '35'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Age', 'operator' : '>', 'value' : '61'}, {'key' : 'Pregnancies', 'operator' : '>', 'value' : '4'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Age', 'operator' : '<=', 'value' : '30'}, {'key' : 'BloodPressure', 'operator' : '>', 'value' : '72'}, {'key' : 'BMI', 'operator' : '<=', 'value' : '42.8'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '<=', 'value' : '89'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '0'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : '1', 'operator' : '=', 'value' : '1'}], 'conclusion' : 'Yes'})

		return rules

	def J48Rules(self):
		
		rules = []
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '<=', 'value' : '127'}, {'key' : 'BMI', 'operator' : '<=', 'value' : '26.4'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '<=', 'value' : '127'}, {'key' : 'BMI', 'operator' : '>', 'value' : '26.4'}, {'key' : 'Age', 'operator' : '<=', 'value' : '28'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '<=', 'value' : '127'}, {'key' : 'BMI', 'operator' : '>', 'value' : '26.4'}, {'key' : 'Age', 'operator' : '>', 'value' : '28'}, {'key' : 'Glucose', 'operator' : '<=', 'value' : '99'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '<=', 'value' : '127'}, {'key' : 'BMI', 'operator' : '>', 'value' : '26.4'}, {'key' : 'Age', 'operator' : '>', 'value' : '28'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '99'}, {'key' : 'DiabetesPedigreeFunction', 'operator' : '<=', 'value' : '0.561'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '<=', 'value' : '127'}, {'key' : 'BMI', 'operator' : '>', 'value' : '26.4'}, {'key' : 'Age', 'operator' : '>', 'value' : '28'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '99'}, {'key' : 'DiabetesPedigreeFunction', 'operator' : '>', 'value' : '0.561'}, {'key' : 'Pregnancies', 'operator' : '<=', 'value' : '6'}, {'key' : 'Age', 'operator' : '<=', 'value' : '30'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '<=', 'value' : '127'}, {'key' : 'BMI', 'operator' : '>', 'value' : '26.4'}, {'key' : 'Age', 'operator' : '>', 'value' : '28'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '99'}, {'key' : 'DiabetesPedigreeFunction', 'operator' : '>', 'value' : '0.561'}, {'key' : 'Pregnancies', 'operator' : '<=', 'value' : '6'}, {'key' : 'Age', 'operator' : '>', 'value' : '30'}, {'key' : 'Age', 'operator' : '<=', 'value' : '34'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '<=', 'value' : '127'}, {'key' : 'BMI', 'operator' : '>', 'value' : '26.4'}, {'key' : 'Age', 'operator' : '>', 'value' : '28'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '99'}, {'key' : 'DiabetesPedigreeFunction', 'operator' : '>', 'value' : '0.561'}, {'key' : 'Pregnancies', 'operator' : '<=', 'value' : '6'}, {'key' : 'Age', 'operator' : '>', 'value' : '30'}, {'key' : 'Age', 'operator' : '>', 'value' : '34'}, {'key' : 'BMI', 'operator' : '<=', 'value' : '33.1'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '<=', 'value' : '127'}, {'key' : 'BMI', 'operator' : '>', 'value' : '26.4'}, {'key' : 'Age', 'operator' : '>', 'value' : '28'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '99'}, {'key' : 'DiabetesPedigreeFunction', 'operator' : '>', 'value' : '0.561'}, {'key' : 'Pregnancies', 'operator' : '<=', 'value' : '6'}, {'key' : 'Age', 'operator' : '>', 'value' : '30'}, {'key' : 'Age', 'operator' : '>', 'value' : '34'}, {'key' : 'BMI', 'operator' : '>', 'value' : '33.1'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '<=', 'value' : '127'}, {'key' : 'BMI', 'operator' : '>', 'value' : '26.4'}, {'key' : 'Age', 'operator' : '>', 'value' : '28'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '99'}, {'key' : 'DiabetesPedigreeFunction', 'operator' : '>', 'value' : '0.561'}, {'key' : 'Pregnancies', 'operator' : '>', 'value' : '6'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '>', 'value' : '127'}, {'key' : 'BMI', 'operator' : '<=', 'value' : '29.9'}, {'key' : 'Glucose', 'operator' : '<=', 'value' : '145'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '>', 'value' : '127'}, {'key' : 'BMI', 'operator' : '<=', 'value' : '29.9'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '145'}, {'key' : 'Age', 'operator' : '<=', 'value' : '25'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '>', 'value' : '127'}, {'key' : 'BMI', 'operator' : '<=', 'value' : '29.9'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '145'}, {'key' : 'Age', 'operator' : '>', 'value' : '25'}, {'key' : 'Age', 'operator' : '<=', 'value' : '61'}, {'key' : 'BMI', 'operator' : '<=', 'value' : '27.1'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '>', 'value' : '127'}, {'key' : 'BMI', 'operator' : '<=', 'value' : '29.9'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '145'}, {'key' : 'Age', 'operator' : '>', 'value' : '25'}, {'key' : 'Age', 'operator' : '<=', 'value' : '61'}, {'key' : 'BMI', 'operator' : '>', 'value' : '27.1'}, {'key' : 'BloodPressure', 'operator' : '<=', 'value' : '82'}, {'key' : 'DiabetesPedigreeFunction', 'operator' : '<=', 'value' : '0.396'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '>', 'value' : '127'}, {'key' : 'BMI', 'operator' : '<=', 'value' : '29.9'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '145'}, {'key' : 'Age', 'operator' : '>', 'value' : '25'}, {'key' : 'Age', 'operator' : '<=', 'value' : '61'}, {'key' : 'BMI', 'operator' : '>', 'value' : '27.1'}, {'key' : 'BloodPressure', 'operator' : '<=', 'value' : '82'}, {'key' : 'DiabetesPedigreeFunction', 'operator' : '>', 'value' : '0.396'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '>', 'value' : '127'}, {'key' : 'BMI', 'operator' : '<=', 'value' : '29.9'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '145'}, {'key' : 'Age', 'operator' : '>', 'value' : '25'}, {'key' : 'Age', 'operator' : '<=', 'value' : '61'}, {'key' : 'BMI', 'operator' : '>', 'value' : '27.1'}, {'key' : 'BloodPressure', 'operator' : '>', 'value' : '82'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '>', 'value' : '127'}, {'key' : 'BMI', 'operator' : '<=', 'value' : '29.9'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '145'}, {'key' : 'Age', 'operator' : '>', 'value' : '25'}, {'key' : 'Age', 'operator' : '>', 'value' : '61'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '>', 'value' : '127'}, {'key' : 'BMI', 'operator' : '>', 'value' : '29.9'}, {'key' : 'Glucose', 'operator' : '<=', 'value' : '157'}, {'key' : 'BloodPressure', 'operator' : '<=', 'value' : '61'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '>', 'value' : '127'}, {'key' : 'BMI', 'operator' : '>', 'value' : '29.9'}, {'key' : 'Glucose', 'operator' : '<=', 'value' : '157'}, {'key' : 'BloodPressure', 'operator' : '>', 'value' : '61'}, {'key' : 'Age', 'operator' : '<=', 'value' : '30'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '>', 'value' : '127'}, {'key' : 'BMI', 'operator' : '>', 'value' : '29.9'}, {'key' : 'Glucose', 'operator' : '<=', 'value' : '157'}, {'key' : 'BloodPressure', 'operator' : '>', 'value' : '61'}, {'key' : 'Age', 'operator' : '>', 'value' : '30'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '>', 'value' : '127'}, {'key' : 'BMI', 'operator' : '>', 'value' : '29.9'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '157'}], 'conclusion' : 'Yes'})
		
		return rules

	def RipperRules(self):

		rules = []
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '=', 'value' : '123.500'}, {'key' : 'BMI', 'operator' : '=', 'value' : '26.950'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '=', 'value' : '127.500'}, {'key' : 'Age', 'operator' : '=', 'value' : '30.500'}, {'key' : 'BMI', 'operator' : '=', 'value' : '30.950'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '=', 'value' : '139.500'}, {'key' : 'Age', 'operator' : '=', 'value' : '30.500'}, {'key' : 'DiabetesPedigreeFunction', 'operator' : '=', 'value' : '0.501'}, {'key' : 'BloodPressure', 'operator' : '>', 'value' : '56'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '>', 'value' : '154.500'}, {'key' : 'DiabetesPedigreeFunction', 'operator' : '>', 'value' : '0.343'}, {'key' : 'Insulin', 'operator' : '=', 'value' : '520'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '=', 'value' : '107.500'}, {'key' : 'Glucose', 'operator' : '=', 'value' : '91.500'}, {'key' : 'SkinThickness', 'operator' : '=', 'value' : '30.500'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Age', 'operator' : '>', 'value' : '24.500'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '106.500'}, {'key' : 'BMI', 'operator' : '>', 'value' : '30.050'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '127.500'}, {'key' : 'Age', 'operator' : '>', 'value' : '42.500'}, {'key' : 'DiabetesPedigreeFunction', 'operator' : '>', 'value' : '0.226'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '=', 'value' : '106.500'}, {'key' : 'DiabetesPedigreeFunction', 'operator' : '=', 'value' : '0.218'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Age', 'operator' : '>', 'value' : '56.500'}, {'key' : 'BMI', 'operator' : '>', 'value' : '24.850'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Insulin', 'operator' : '=', 'value' : '38.500'}, {'key' : 'BMI', 'operator' : '>', 'value' : '37.550'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '129.500'}, {'key' : 'SkinThickness', 'operator' : '=', 'value' : '50'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'Age', 'operator' : '=', 'value' : '27.500'}, {'key' : 'BloodPressure', 'operator' : '>', 'value' : '71'}, {'key' : 'Glucose', 'operator' : '=', 'value' : '168'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'DiabetesPedigreeFunction', 'operator' : '=', 'value' : '0.234'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '163'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'DiabetesPedigreeFunction', 'operator' : '>', 'value' : '0.740'}, {'key' : 'BMI', 'operator' : '=', 'value' : '36.650'}, {'key' : 'BloodPressure', 'operator' : '>', 'value' : '76'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'BloodPressure', 'operator' : '=', 'value' : '74.500'}, {'key' : 'SkinThickness', 'operator' : '=', 'value' : '9.500'}, {'key' : 'BMI', 'operator' : '>', 'value' : '29.850'}, {'key' : 'BMI', 'operator' : '=', 'value' : '34.850'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'Insulin', 'operator' : '=', 'value' : '85.500'}, {'key' : 'Age', 'operator' : '=', 'value' : '40.500'}, {'key' : 'SkinThickness', 'operator' : '>', 'value' : '37.500'}, {'key' : 'BloodPressure', 'operator' : '>', 'value' : '69'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'SkinThickness', 'operator' : '=', 'value' : '21.500'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '126.500'}, {'key' : 'Glucose', 'operator' : '=', 'value' : '138.500'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Insulin', 'operator' : '>', 'value' : '121'}, {'key' : 'BloodPressure', 'operator' : '>', 'value' : '77'}, {'key' : 'DiabetesPedigreeFunction', 'operator' : '=', 'value' : '0.427'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'BMI', 'operator' : '>', 'value' : '40.800'}, {'key' : 'Pregnancies', 'operator' : '>', 'value' : '7.500'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'Age', 'operator' : '=', 'value' : '24.500'}, {'key' : 'BMI', 'operator' : '=', 'value' : '33.200'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Age', 'operator' : '>', 'value' : '40.500'}, {'key' : 'BloodPressure', 'operator' : '=', 'value' : '77'}, {'key' : 'BMI', 'operator' : '>', 'value' : '35.450'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'BMI', 'operator' : '>', 'value' : '35.200'}, {'key' : 'BMI', 'operator' : '=', 'value' : '40.800'}, {'key' : 'SkinThickness', 'operator' : '>', 'value' : '27.500'}, {'key' : 'Glucose', 'operator' : '>', 'value' : '113'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Insulin', 'operator' : '>', 'value' : '126.500'}, {'key' : 'Age', 'operator' : '=', 'value' : '33.500'}, {'key' : 'DiabetesPedigreeFunction', 'operator' : '>', 'value' : '0.639'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'DiabetesPedigreeFunction', 'operator' : '>', 'value' : '0.377'}, {'key' : 'Glucose', 'operator' : '=', 'value' : '102'}, {'key' : 'Insulin', 'operator' : '=', 'value' : '86.500'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'BMI', 'operator' : '=', 'value' : '29.100'}, {'key' : 'BMI', 'operator' : '>', 'value' : '27.800'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'DiabetesPedigreeFunction', 'operator' : '=', 'value' : '0.242'}, {'key' : 'BMI', 'operator' : '>', 'value' : '34.050'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'Insulin', 'operator' : '>', 'value' : '99.500'}, {'key' : 'Age', 'operator' : '=', 'value' : '29.500'}, {'key' : 'Age', 'operator' : '=', 'value' : '37.500'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'BMI', 'operator' : '=', 'value' : '33.850'}, {'key' : 'DiabetesPedigreeFunction', 'operator' : '=', 'value' : '0.361'}, {'key' : 'BMI', 'operator' : '>', 'value' : '28.500'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'Age', 'operator' : '>', 'value' : '36'}, {'key' : 'BMI', 'operator' : '>', 'value' : '29.950'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'Glucose', 'operator' : '=', 'value' : '117'}, {'key' : 'BMI', 'operator' : '=', 'value' : '36.700'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : 'SkinThickness', 'operator' : '=', 'value' : '19.500'}, {'key' : 'DiabetesPedigreeFunction', 'operator' : '>', 'value' : '0.242'}], 'conclusion' : 'No'})
		rules.append({'conditions' : [{'key' : 'DiabetesPedigreeFunction', 'operator' : '=', 'value' : '0.435'}, {'key' : 'Glucose', 'operator' : '=', 'value' : '161.500'}], 'conclusion' : 'Yes'})
		rules.append({'conditions' : [{'key' : '1', 'operator' : '=', 'value' : '1'}], 'conclusion' : 'No'})

		return rules


# pidObj = PIDDSRules()

# dtRules = pidObj.DTRules()
# print('total DT Rules: ', len(dtRules))

# partRules = pidObj.PartRules()
# print('total PART Rules: ', len(partRules))

# j48Rules = pidObj.J48Rules()
# print('total J48 Rules: ', len(j48Rules))

# ripperRules = pidObj.RipperRules()
# print('total Ripper Rules: ', len(ripperRules))






		